<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <IsPackable>false</IsPackable>
  <OutputType>Exe</OutputType>
  <TestingPlatformCommandLineArguments>--report-trx --report-trx-filename test-results.trx --coverlet --coverlet-output-format cobertura --coverlet-include "[MemoAna.Backend]*,[MemoAna.Backend.Application]*,[MemoAna.Backend.Domain]*,[MemoAna.Backend.Infrastructure]*" --coverlet-exclude "[*.Migrations]*,[*.UnitTests]*,[Mediator*]*,[FluentValidation*]*,[MemoAna.Backend]AspNetCoreGeneratedDocument.*,[MemoAna.Backend]*.Components.*,[MemoAna.Backend]*.Pages.*,[MemoAna.Backend]*.Layout.*,[MemoAna.Backend]*.Shared.*"</TestingPlatformCommandLineArguments>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.3">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" Version="6.2.0" />
    <PackageReference Include="xunit.v3" Version="4.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Include="testconfig.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
 
  <ItemGroup>
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend\MemoAna.Backend.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Application\MemoAna.Backend.Application.csproj" />
    <ProjectReference
      Include="..\..\..\src\web\MemoAna.Backend.Infrastructure\MemoAna.Backend.Infrastructure.csproj" />
  </ItemGroup>

</Project>